CREATE TYPE rol_usuario AS ENUM ('OWNER', 'ADMIN', 'CAJERO');
CREATE TYPE plan_suscripcion AS ENUM ('TRIAL', 'BASICO', 'PRO');
CREATE TYPE estado_suscripcion AS ENUM ('ACTIVA', 'VENCIDA', 'CANCELADA', 'PAUSADA');
CREATE TYPE estado_pedido AS ENUM ('PENDIENTE', 'CONFIRMADO', 'EN_PREPARACION', 'ENTREGADO', 'CANCELADO');
CREATE TYPE canal_pedido AS ENUM ('WHATSAPP', 'PRESENCIAL', 'WEB');
CREATE TYPE tipo_movimiento AS ENUM ('ENTRADA', 'SALIDA', 'AJUSTE_MANUAL');
